-- FINAL CONSOLIDATED PRODUCTION MIGRATION SCRIPT
-- USE THIS SCRIPT TO SYNC ALL DATABASE CHANGES AT ONCE

-- 1. USERS TABLE ENHANCEMENTS
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_pic VARCHAR(255) DEFAULT 'default.jpg';
ALTER TABLE users ADD COLUMN IF NOT EXISTS bank_name VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS account_number VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS ifsc_code VARCHAR(20);

-- 2. SALARY STRUCTURES (35+ Fields Expansion)
ALTER TABLE salary_structures 
ADD COLUMN IF NOT EXISTS hra DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS da DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS special_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS conveyance_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS medical_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS education_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS uniform_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS food_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS telephone_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS books_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS research_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS cca DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS transport_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS pf_deduction DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS tax_deduction DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS pf_employer_contribution DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS eps_contribution DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS esi_employer_contribution DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS gratuity_provision DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS bonus_provision DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS lwf_employee DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS lwf_employer DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS surcharge DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS advance_recovery DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS loan_emi DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS tds_monthly DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS professional_tax DECIMAL(10,2) DEFAULT 200,
ADD COLUMN IF NOT EXISTS deduction_80c DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS deduction_80d DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prev_employer_tds DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_working_days INT DEFAULT 26,
ADD COLUMN IF NOT EXISTS is_statutory_enabled TINYINT(1) DEFAULT 1;

-- 3. PAYROLL HISTORY (Snapshots, CTC, LOP & Unique Key)
ALTER TABLE payroll_history
ADD COLUMN IF NOT EXISTS lop_deductions DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS breakdown_json TEXT,
ADD COLUMN IF NOT EXISTS monthly_ctc DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS annual_ctc DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS processed_by INT,
ADD COLUMN IF NOT EXISTS is_statutory_enabled TINYINT(1) DEFAULT 1;

-- Add Unique Key to prevent duplicate history records per month
-- Standard MySQL does not support IF NOT EXISTS for indexes in older versions. 
-- Best to run and ignore duplicate key errors if already present.
-- ALTER TABLE payroll_history ADD UNIQUE KEY uk_user_month_year (user_id, month, year);

-- 4. LEAVE MANAGEMENT TABLES
CREATE TABLE IF NOT EXISTS leave_types (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    quarterly_allocation DECIMAL(10,2) DEFAULT 1.5,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS leave_allocations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    leave_type_id INT NOT NULL,
    quarter INT NOT NULL,
    year INT NOT NULL,
    allocated DECIMAL(10,2) DEFAULT 0,
    used DECIMAL(10,2) DEFAULT 0,
    UNIQUE KEY (user_id, leave_type_id, quarter, year)
);

-- Seed Default Leave Types
INSERT INTO leave_types (name, quarterly_allocation) VALUES 
('Sick Leave', 1.5),
('Casual Leave', 1.5),
('Earned Leave', 3.0)
ON DUPLICATE KEY UPDATE quarterly_allocation = VALUES(quarterly_allocation);

-- 5. PERFORMANCE & MISC FIXES
ALTER TABLE travel_summary MODIFY COLUMN total_distance DECIMAL(10,2) DEFAULT 0.00;
