-- FULL HRMS ADVANCED PRODUCTION MIGRATION SCRIPT
-- This script contains ALL schema changes for Advanced Payroll, Leave Management, and Statutory Toggles.

-- 1. SALARY STRUCTURES (35+ Fields Expansion)
ALTER TABLE salary_structures 
ADD COLUMN IF NOT EXISTS hra DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS da DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS special_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS conveyance_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS medical_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS education_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS uniform_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS food_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS telephone_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS books_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS research_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS cca DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS transport_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS pf_deduction DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS tax_deduction DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS pf_employer_contribution DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS eps_contribution DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS esi_employer_contribution DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS gratuity_provision DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS bonus_provision DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS lwf_employee DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS lwf_employer DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS surcharge DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS advance_recovery DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS loan_emi DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS tds_monthly DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS professional_tax DECIMAL(10,2) DEFAULT 200,
ADD COLUMN IF NOT EXISTS deduction_80c DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS deduction_80d DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prev_employer_tds DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_working_days INT DEFAULT 26,
ADD COLUMN IF NOT EXISTS is_statutory_enabled TINYINT(1) DEFAULT 1;

-- 2. PAYROLL HISTORY (Snapshots, CTC, Statutory Flag)
ALTER TABLE payroll_history
ADD COLUMN IF NOT EXISTS breakdown_json TEXT,
ADD COLUMN IF NOT EXISTS monthly_ctc DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS annual_ctc DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_statutory_enabled TINYINT(1) DEFAULT 1;

-- 3. LEAVE STRUCTURES (If missing tables or columns)
CREATE TABLE IF NOT EXISTS leave_types (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    quarterly_allocation DECIMAL(10,2) DEFAULT 1.5,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS leave_allocations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    leave_type_id INT NOT NULL,
    quarter INT NOT NULL,
    year INT NOT NULL,
    allocated DECIMAL(10,2) DEFAULT 0,
    used DECIMAL(10,2) DEFAULT 0,
    UNIQUE KEY (user_id, leave_type_id, quarter, year)
);

-- 4. SEED DEFAULT LEAVE TYPES
INSERT INTO leave_types (name, quarterly_allocation) VALUES 
('Sick Leave', 1.5),
('Casual Leave', 1.5),
('Earned Leave', 3.0)
ON DUPLICATE KEY UPDATE quarterly_allocation = VALUES(quarterly_allocation);

-- 5. ATTENDANCE & TRACKING TABLES (Ensure proper decimal precision if altered)
ALTER TABLE travel_summary MODIFY COLUMN total_distance DECIMAL(10,2) DEFAULT 0.00;
