-- Enterprise Payroll Module Production Migration Script
-- Run this on your production database to support Advanced Salary & CTC features.

-- 1. Expand Salary Structures to support 35+ components
ALTER TABLE salary_structures 
ADD COLUMN IF NOT EXISTS hra DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS da DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS special_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS conveyance_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS medical_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS education_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS uniform_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS food_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS telephone_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS books_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS research_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS cca DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS transport_allowance DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS pf_deduction DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS tax_deduction DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS pf_employer_contribution DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS eps_contribution DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS esi_employer_contribution DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS gratuity_provision DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS bonus_provision DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS lwf_employee DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS lwf_employer DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS surcharge DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS advance_recovery DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS loan_emi DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS tds_monthly DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS professional_tax DECIMAL(10,2) DEFAULT 200,
ADD COLUMN IF NOT EXISTS deduction_80c DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS deduction_80d DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS prev_employer_tds DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_working_days INT DEFAULT 26,
ADD COLUMN IF NOT EXISTS is_statutory_enabled TINYINT(1) DEFAULT 1;

-- 2. Expand Payroll History for snapshots and CTC auditing
ALTER TABLE payroll_history
ADD COLUMN IF NOT EXISTS breakdown_json TEXT,
ADD COLUMN IF NOT EXISTS monthly_ctc DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS annual_ctc DECIMAL(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_statutory_enabled TINYINT(1) DEFAULT 1;

-- 3. Ensure proper data types for existing fields (if needed)
ALTER TABLE salary_structures MODIFY COLUMN basic DECIMAL(10,2) DEFAULT 0;
ALTER TABLE salary_structures MODIFY COLUMN total_ctc DECIMAL(10,2) DEFAULT 0;
